/**
 * PHASE 0 — Deterministic UUID v5 Generator
 *
 * Server-side only (uses Node.js `crypto` module).
 *
 * IMPLEMENTS: UUID v5 per RFC 4122 (SHA-1 based, deterministic).
 *   - Same namespace + name → ALWAYS produces the same UUID.
 *   - This UUID is the "stable key" used for matching rows across re-imports.
 *   - The DB primary key (uuid column) is set to this value on first INSERT.
 *   - On re-import: find row by stable key → UPDATE, never change UUID.
 *
 * NAMESPACE STRATEGY:
 *   Each entity type has its own sub-namespace UUID to prevent collisions
 *   between a PDCA master record and an action that happens to share the
 *   same string key. All namespaces are fixed and must NEVER be changed.
 *
 * IDENTITY INPUTS per entity type:
 *   pdca_master   → pdca_id
 *   pdca_action   → pdca_id + phase + action_id
 *   pdca_subaction → pdca_id + phase + action_id + subaction_id
 */

import { createHash } from "crypto";

// ─────────────────────────────────────────────
// FIXED NAMESPACE UUIDS
// These are UUID v4 values generated once and frozen permanently.
// Changing them would invalidate all existing stable keys.
// ─────────────────────────────────────────────

/** Root namespace for this PDCA SGQ system. */
const NS_ROOT = "f47ac10b-58cc-4372-a567-0e02b2c3d479";

/** Sub-namespaces per entity type (derived via uuidV5 from NS_ROOT). */
export const PDCA_NAMESPACES = {
  MASTER: uuidV5("pdca:master", NS_ROOT),
  ACTION: uuidV5("pdca:action", NS_ROOT),
  SUBACTION: uuidV5("pdca:subaction", NS_ROOT),
} as const;

// ─────────────────────────────────────────────
// UUID v5 IMPLEMENTATION (RFC 4122)
// ─────────────────────────────────────────────

function hexToBytes(hex: string): Buffer {
  return Buffer.from(hex.replace(/-/g, ""), "hex");
}

function bytesToUuid(bytes: Buffer): string {
  const h = bytes.toString("hex");
  return [
    h.slice(0, 8),
    h.slice(8, 12),
    h.slice(12, 16),
    h.slice(16, 20),
    h.slice(20, 32),
  ].join("-");
}

/**
 * Generate a UUID v5 from a namespace UUID and a name string.
 * RFC 4122 §4.3 compliant.
 *
 * @param name      - The name to hash (e.g., "PDCA-01:PLAN:P1")
 * @param namespace - A UUID string to use as namespace (default: NS_ROOT)
 * @returns         - Deterministic UUID string
 */
export function uuidV5(name: string, namespace: string = NS_ROOT): string {
  const nsBytes = hexToBytes(namespace);
  const nameBytes = Buffer.from(name, "utf8");

  const hash = createHash("sha1")
    .update(nsBytes)
    .update(nameBytes)
    .digest();

  // Set version bits to 0101 (v5) in octet 6
  hash[6] = (hash[6] & 0x0f) | 0x50;
  // Set variant bits to 10 (RFC 4122) in octet 8
  hash[8] = (hash[8] & 0x3f) | 0x80;

  return bytesToUuid(hash.slice(0, 16));
}

// ─────────────────────────────────────────────
// ENTITY STABLE KEYS
// ─────────────────────────────────────────────

/**
 * Stable UUID for a PDCA master record.
 * Identity: pdca_id alone.
 */
export function pdcaMasterUuid(pdcaId: string): string {
  return uuidV5(pdcaId, PDCA_NAMESPACES.MASTER);
}

/**
 * Stable UUID for an action within a PDCA phase.
 * Identity: pdca_id + phase + action_id.
 *
 * IMPORTANT: action_id ("P1", "D2") is the VISUAL identifier from Excel,
 * NOT a sequential counter. Two actions with the same visual ID in the same
 * PDCA+phase are the same logical entity.
 */
export function pdcaActionUuid(
  pdcaId: string,
  phase: string,
  actionId: string
): string {
  const name = [pdcaId, phase.toUpperCase(), actionId].join(":");
  return uuidV5(name, PDCA_NAMESPACES.ACTION);
}

/**
 * Stable UUID for a subaction/task.
 * Identity: pdca_id + phase + action_id + subaction_id.
 *
 * If subaction_id changes (e.g., "SP.1" renumbered to "SP.2"),
 * this produces a NEW UUID → treated as a new entity, old one marked "removed".
 * This is the correct behavior: renumbering is a structural change.
 */
export function pdcaSubactionUuid(
  pdcaId: string,
  phase: string,
  actionId: string,
  subactionId: string
): string {
  const name = [pdcaId, phase.toUpperCase(), actionId, subactionId].join(":");
  return uuidV5(name, PDCA_NAMESPACES.SUBACTION);
}

// ─────────────────────────────────────────────
// VERIFICATION UTILITY
// ─────────────────────────────────────────────

/**
 * Verify that a UUID was generated by this system for the given inputs.
 * Use in audit contexts to confirm traceability.
 */
export function verifySubactionUuid(
  candidate: string,
  pdcaId: string,
  phase: string,
  actionId: string,
  subactionId: string
): boolean {
  return candidate === pdcaSubactionUuid(pdcaId, phase, actionId, subactionId);
}

export function verifyActionUuid(
  candidate: string,
  pdcaId: string,
  phase: string,
  actionId: string
): boolean {
  return candidate === pdcaActionUuid(pdcaId, phase, actionId);
}
